name: firebase_tutorial
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  email_validator: ^2.1.17
  firebase_auth: ^4.11.1
  firebase_core: ^2.19.0
  firebase_database: ^10.3.1
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
